### ISSUE TITLE
Lua error: Comparing `number < boolean` in Scanner

### ISSUE THREAD

**Issue by pallen0304** [Baertram/ResearchAssistant#5] opened 2022-09-17 16:07 UTC
Experiencing issue in 0.9.5.7 intermittently where Lua error is thrown saying "operator < is not supported for number < boolean".
[Affected code](https://github.com/Baertram/ResearchAssistant/blob/67e726996afae2ee78091c382128fd4b71fc51ba/ResearchAssistant/ResearchAssistantScanner.lua#L265-L278)
![image](https://user-images.githubusercontent.com/4258736/190863165-65171663-5358-4c75-97f7-f687a3ce849b.png)

The error is occuring when making comparison "value < compareValue", in which a number is stored in value and compareValue is a boolean (false/true). If I understand the code correctly, this means that in a previous iteration of this method, this if block resolved true and value was True, but value was a number in a later iteration. If I understand correctly, Value should never be a number. I don't think I understand. :)
![image](https://user-images.githubusercontent.com/4258736/190863507-614637c1-a9ab-4a87-bf55-18787c8acd27.png)

Would appreciate if someone with a better understanding of this codebase and Lua took a look and figured out the best way to handle this.

**Comment by Baertram** [comment] 2022-09-17 18:49
Ah damn I thought I had fixed that already, there is missing a boolean check. I'll add this

**Comment by pallen0304** [comment] 2022-09-17 20:58
This was my first time experiencing an issue with this addon. The error doesn't occur every time I load in to game or /reloadui, so it's difficult to narrow down if reproducing isn't consistent. After swapping the function out for that code replacement, I wasn't able to reproduce on initial login or several times running /reloadui. My inventory hasn't changed since earlier. I'm thinking that fixed it. Appears to function as expected.

**Comment by Baertram** [comment] 2024-08-11 11:20
Should be fixed meanwhile and so far I could not reproduce it anymore.
If it happens most likely SavedVariables got corrupted due to client crash etc.

**Closed by Baertram** 2024-08-11 11:20 UTC
